apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\oc\v3.9.0\windows\kompose.exe convert -f prod-docker-compose.yml
      --provider openshift
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: wacore
  name: wacore
spec:
  ports:
  - name: "6250"
    port: 6250
    targetPort: 6250
  - name: "6251"
    port: 6251
    targetPort: 6251
  - name: "6252"
    port: 6252
    targetPort: 6252
  - name: "6253"
    port: 6253
    targetPort: 6253
  selector:
    io.kompose.service: wacore
status:
  loadBalancer: {}
