apiVersion: v1
data:
  WA_DB_ENGINE: MYSQL
  WA_DB_HOSTNAME: db
  WA_DB_PASSWORD: testpass
  WA_DB_PORT: "3306"
  WA_DB_USERNAME: root
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waweb-db-env
  name: waweb-db-env
