apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\oc\v3.9.0\windows\kompose.exe convert -f prod-docker-compose.yml
      --provider openshift
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: waweb
  name: waweb
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 443
  selector:
    io.kompose.service: waweb
status:
  loadBalancer: {}
