apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\oc\v3.9.0\windows\kompose.exe convert -f prod-docker-compose.yml
      --provider openshift
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: waweb
  name: waweb
spec:
  replicas: 1
  selector:
    io.kompose.service: waweb
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: waweb
    spec:
      serviceAccountName: chatbot-sa
      containers:
      - args:
        - /opt/whatsapp/bin/wait_on_mysql.sh
        - /opt/whatsapp/bin/launch_within_docker.sh
        env:
        - name: ORCHESTRATION
          value: DOCKER-COMPOSE
        - name: WACORE_HOSTNAME
          value: wacore
        - name: WA_DB_ENGINE
          valueFrom:
            configMapKeyRef:
              key: WA_DB_ENGINE
              name: waweb-db-env
        - name: WA_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: WA_DB_HOSTNAME
              name: waweb-db-env
        - name: WA_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: WA_DB_PASSWORD
              name: waweb-db-env
        - name: WA_DB_PORT
          valueFrom:
            configMapKeyRef:
              key: WA_DB_PORT
              name: waweb-db-env
        - name: WA_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: WA_DB_USERNAME
              name: waweb-db-env
        - name: WA_RUNNING_ENV_VERSION
          value: v2.2.2
        image: ' '
        name: waweb
        ports:
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/wamedia
          name: whatsappmedia
      restartPolicy: Always
      volumes:
      - name: whatsappmedia
        persistentVolumeClaim:
          claimName: whatsappmedia
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - waweb
      from:
        kind: ImageStreamTag
        name: waweb:v2.21.6
    type: ImageChange
status: {}
