apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\oc\v3.11.0\kompose.exe convert -f prod-multiconnect-compose.yml
      --provider openshift
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: wawebmulticonnect
  name: wawebmulticonnect
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 443
  selector:
    io.kompose.service: wawebmulticonnect
status:
  loadBalancer: {}
